spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/zpm
    username: zpm
    password: zpm
    driver-class-name: com.mysql.jdbc.Driver
  http:
    encoding:
      charset: UTF-8
      enabled: true
  flyway:
    enabled: false
